### ISSUE TITLE
Iron Router seems to be breaking this

### ISSUE THREAD

**Issue by ghost** [hugesuccess/facebook-sdk#11]
Iron-router seems to break the functionality of the Facebook Javascript SDK.

I want to display a popup through which a logged in user can send a private message to their friend on Facebook.

After doing

```
window.fbAsyncInit = ->
    FB.init({appId: fb_app_id, status: true, xfbml: true})
```

I call

```
FB.ui({method: 'send', app_id: fb_app_id, to: fb_object.fb_id, link: link, display: 'iframe'}, (response) ->
    ...
)
```

This works great when the route is first loaded. But if I go to another route, then come back to this one, then try to call the above FB.ui method, it fails:

```
Error
    at Object.<anonymous> (http://connect.facebook.net/en_US/all/debug.js:1787:26)
    at window.FB.__w.signature (http://connect.facebook.net/en_US/all/debug.js:449:20)
    at window.FB.__w.signature (http://connect.facebook.net/en_US/all/debug.js:445:46)
    at window.FB.__w.signature (http://connect.facebook.net/en_US/all/debug.js:445:46)
    at window.FB.__w.signature (http://connect.facebook.net/en_US/all/debug.js:445:46)
    at window.FB.__w.signature (http://connect.facebook.net/en_US/all/debug.js:445:46)
    at window.FB.__w.signature (http://connect.facebook.net/en_US/all/debug.js:445:46)
    at window.FB.__w.signature (http://connect.facebook.net/en_US/all/debug.js:445:46)
    at window.FB.__w.signature (http://connect.facebook.net/en_US/all/debug.js:445:46)
    at window.FB.__w.signature (http://connect.facebook.net/en_US/all/debug.js:445:46) 
```

What is causing this? How do you get around it? Thanks.

**Comment by ghost** [comment]
Figured it out. For anyone who is having this problem, here is how I solved it.

I was placing my `<div id='fb-root'></div>` element inside layout templates. This meant that every time I switched pages or executed a route, that element would be re-rendered. I believe the Facebook SDK keeps track of that element, and since the FB SDK is only initialized once, if that element is re-rendered, I guess it loses track of it and fails.

The solution is to place `<div id='fb-root'></div>` directly inside the `<body></body>` so that it doesn't get re-rendered every time a route is executed.

**Comment by hugesuccess** [comment]
Keep in mind that the FB SDK will add the fb-root div automagically if it is not present at runtime. I recommend the lazy developer approach, don't add the div at all and let the SDK add it programatically.
